pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                sh 'javac -encoding UTF-8 -d classes book_manager/src/book_manager/*.java'
            }
        }
        
        stage('Test') {
            steps {
                def classpath = "classes:/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar"
                sh 'java -cp $classpath org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt'
            }
        }
    }
    
    post {
        always {
            archiveArtifacts 'test_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}